import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#1A1B25',
    fontFamily: 'Cochin',
    padding: 5,
  },
  // Home Screen
  h1: {
    color: '#DFF8EB',
    fontSize: 25,
    padding: 0,
    margin: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    paddingBottom: 0,
    textShadowOffset: {
      width: 1,
      height: 2,
    },
    textShadowColor: '#592941',
    textShadowRadius: 1,
  },
  h2: {
    fontStyle: 'italic',
    fontSize: 10,
    color: '#72705B',
    margin: 0, //margin: 20,
    paddingTop: 0,
    alignContent: 'center',
    paddingTop: 0,
    paddingBottom: 5,
  },
  textInput: {
    borderColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    alignContent: 'center',
    textAlign: 'center',
    width: '100%',
    padding: 10,
    margin: 10,
    color: 'white',
    backgroundColor: 'grey',
  },
  appButtonContainer: {
    elevation: 8,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appButtonText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  checkbox: {
    alignSelf: 'center',
  },
  label: {
    margin: 8,
  },
  text: {
    margin: 7,
    padding: 2,
    color: 'white',
  },
  // flatlist in Modal Screen + Storage
  flatlistContainer: {
    flex: 1,
    backgroundColor: '#F0EFF4',
    marginTop: 1,
  },
  item: {
    position: 'relative',
    width: 100,
    height: 100,
    flex: 3,
    padding: 1,
    alignItems: 'center',
    overflow: 'hidden',
  },
  itemFromStorage: {
    position: 'relative',
    width: 100,
    height: 100,
    flex: 3,
    padding: 1,
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 7,
    margin: 5,
  },
  title: {
    fontSize: 12,
    color: 'white',
    opacity: 0.8,
    fontWeight: '200',
    letterSpacing: 1,
    textTransform: 'capitalize',
    position: 'absolute',
    overflow: 'hidden',
    textShadowColor: '#000000',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 10,
    textAlign: 'center',
  },
  logo: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'white',
    alignItems: 'center',
    textAlignVertical: 'bottom',
    overflow: 'hidden',
  },
  logoFromStorage: {
    flex: 1,
    resizeMode: 'cover',
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'white',
    overflow: 'hidden',
  },
  // Panorama Screen
  wrapper: {
    alignItems: 'stretch',
    resizeMode: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  viewer: {
    flexGrow: 1,
    height: 200,
    flex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  wrapperInfoBox: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    position: 'absolute',
    bottom: 0,
    width: '100%',

    zIndex: 3,
    alignContent: 'space-between',
  },
  infoBox: {
    flexDirection: 'column',
    flex: 3,
    zIndex: 4,
  },
  textInfo: {
    fontSize: 13,
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'left',
    overflow: 'hidden',
    textShadowColor: '#F0EFF4',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 5,
    textAlign: 'left',
    fontStyle: 'italic',
    textDecorationLine: 'underline',
  },
  subTextInfo: {
    textTransform: 'capitalize',
    color: '#090446',
    fontStyle: 'italic',
  },
  downloadBtn: {
    flex: 1,
    elevation: 8,
    borderRadius: 100,
    borderColor: '#fff',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
    opacity: 0.7,
  },
  // footer
  footerText: {
    textAlign: 'center',
    color: 'black',
    top: 0,
    fontStyle: 'italic',
    fontSize: 14,
    color: '#72705B',
    padding: 5,
  },
});
